// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBooleanOperations_IndexedDataMapOfShapeAncestorsSuccessors.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _XBooleanOperations_AncestorsSeqAndSuccessorsSeq_HeaderFile
#include <XBooleanOperations_AncestorsSeqAndSuccessorsSeq.hxx>
#endif
#ifndef _TopTools_ShapeMapHasher_HeaderFile
#include <TopTools_ShapeMapHasher.hxx>
#endif
#ifndef _XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeAncestorsSuccessors_HeaderFile
#include <XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeAncestorsSuccessors.hxx>
#endif
 

#define TheKey TopoDS_Shape
#define TheKey_hxx <TopoDS_Shape.hxx>
#define TheItem XBooleanOperations_AncestorsSeqAndSuccessorsSeq
#define TheItem_hxx <XBooleanOperations_AncestorsSeqAndSuccessorsSeq.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <TopTools_ShapeMapHasher.hxx>
#define TCollection_IndexedDataMapNode XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeAncestorsSuccessors
#define TCollection_IndexedDataMapNode_hxx <XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeAncestorsSuccessors.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeAncestorsSuccessors
#define TCollection_IndexedDataMapNode_Type_() XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeAncestorsSuccessors_Type_()
#define TCollection_IndexedDataMap XBooleanOperations_IndexedDataMapOfShapeAncestorsSuccessors
#define TCollection_IndexedDataMap_hxx <XBooleanOperations_IndexedDataMapOfShapeAncestorsSuccessors.hxx>
#include <TCollection_IndexedDataMap.gxx>

