// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeInteger.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _TopTools_ShapeMapHasher_HeaderFile
#include <TopTools_ShapeMapHasher.hxx>
#endif
#ifndef _XBooleanOperations_IndexedDataMapOfShapeInteger_HeaderFile
#include <XBooleanOperations_IndexedDataMapOfShapeInteger.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeInteger)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeInteger)


IMPLEMENT_DOWNCAST(XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeInteger,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeInteger)


#define TheKey TopoDS_Shape
#define TheKey_hxx <TopoDS_Shape.hxx>
#define TheItem Standard_Integer
#define TheItem_hxx <Standard_Integer.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <TopTools_ShapeMapHasher.hxx>
#define TCollection_IndexedDataMapNode XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeInteger
#define TCollection_IndexedDataMapNode_hxx <XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeInteger.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeInteger
#define TCollection_IndexedDataMapNode_Type_() XBooleanOperations_IndexedDataMapNodeOfIndexedDataMapOfShapeInteger_Type_()
#define TCollection_IndexedDataMap XBooleanOperations_IndexedDataMapOfShapeInteger
#define TCollection_IndexedDataMap_hxx <XBooleanOperations_IndexedDataMapOfShapeInteger.hxx>
#include <TCollection_IndexedDataMapNode.gxx>

