// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListIteratorOfListOfCoupleOfInteger.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTools_ListOfCoupleOfInteger_HeaderFile
#include <XBOPTools_ListOfCoupleOfInteger.hxx>
#endif
#ifndef _XBOPTools_CoupleOfInteger_HeaderFile
#include <XBOPTools_CoupleOfInteger.hxx>
#endif
#ifndef _XBOPTools_ListNodeOfListOfCoupleOfInteger_HeaderFile
#include <XBOPTools_ListNodeOfListOfCoupleOfInteger.hxx>
#endif
 

#define Item XBOPTools_CoupleOfInteger
#define Item_hxx <XBOPTools_CoupleOfInteger.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfCoupleOfInteger
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfCoupleOfInteger.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfCoupleOfInteger
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfCoupleOfInteger.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfCoupleOfInteger
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfCoupleOfInteger_Type_()
#define TCollection_List XBOPTools_ListOfCoupleOfInteger
#define TCollection_List_hxx <XBOPTools_ListOfCoupleOfInteger.hxx>
#include <TCollection_ListIterator.gxx>

