// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_SequenceNodeOfSequenceOfPaveBlock.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTools_PaveBlock_HeaderFile
#include <XBOPTools_PaveBlock.hxx>
#endif
#ifndef _XBOPTools_SequenceOfPaveBlock_HeaderFile
#include <XBOPTools_SequenceOfPaveBlock.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_SequenceNodeOfSequenceOfPaveBlock)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_SequenceNodeOfSequenceOfPaveBlock)


IMPLEMENT_DOWNCAST(XBOPTools_SequenceNodeOfSequenceOfPaveBlock,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_SequenceNodeOfSequenceOfPaveBlock)


#define SeqItem XBOPTools_PaveBlock
#define SeqItem_hxx <XBOPTools_PaveBlock.hxx>
#define TCollection_SequenceNode XBOPTools_SequenceNodeOfSequenceOfPaveBlock
#define TCollection_SequenceNode_hxx <XBOPTools_SequenceNodeOfSequenceOfPaveBlock.hxx>
#define Handle_TCollection_SequenceNode Handle_XBOPTools_SequenceNodeOfSequenceOfPaveBlock
#define TCollection_SequenceNode_Type_() XBOPTools_SequenceNodeOfSequenceOfPaveBlock_Type_()
#define TCollection_Sequence XBOPTools_SequenceOfPaveBlock
#define TCollection_Sequence_hxx <XBOPTools_SequenceOfPaveBlock.hxx>
#include <TCollection_SequenceNode.gxx>

