// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListNodeOfListOfCommonBlock.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTools_CommonBlock_HeaderFile
#include <XBOPTools_CommonBlock.hxx>
#endif
#ifndef _XBOPTools_ListOfCommonBlock_HeaderFile
#include <XBOPTools_ListOfCommonBlock.hxx>
#endif
#ifndef _XBOPTools_ListIteratorOfListOfCommonBlock_HeaderFile
#include <XBOPTools_ListIteratorOfListOfCommonBlock.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_ListNodeOfListOfCommonBlock)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_ListNodeOfListOfCommonBlock)


IMPLEMENT_DOWNCAST(XBOPTools_ListNodeOfListOfCommonBlock,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_ListNodeOfListOfCommonBlock)


#define Item XBOPTools_CommonBlock
#define Item_hxx <XBOPTools_CommonBlock.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfCommonBlock
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfCommonBlock.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfCommonBlock
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfCommonBlock.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfCommonBlock
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfCommonBlock_Type_()
#define TCollection_List XBOPTools_ListOfCommonBlock
#define TCollection_List_hxx <XBOPTools_ListOfCommonBlock.hxx>
#include <TCollection_ListNode.gxx>

