// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IndexedDataMapOfIntegerPaveSet.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTools_PaveSet_HeaderFile
#include <XBOPTools_PaveSet.hxx>
#endif
#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet_HeaderFile
#include <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet.hxx>
#endif
 

#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem XBOPTools_PaveSet
#define TheItem_hxx <XBOPTools_PaveSet.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet
#define TCollection_IndexedDataMapNode_hxx <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet
#define TCollection_IndexedDataMapNode_Type_() XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet_Type_()
#define TCollection_IndexedDataMap XBOPTools_IndexedDataMapOfIntegerPaveSet
#define TCollection_IndexedDataMap_hxx <XBOPTools_IndexedDataMapOfIntegerPaveSet.hxx>
#include <TCollection_IndexedDataMap.gxx>

