// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IMapOfPaveBlock.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _XBOPTools_PaveBlock_HeaderFile
#include <XBOPTools_PaveBlock.hxx>
#endif
#ifndef _XBOPTools_PaveBlockMapHasher_HeaderFile
#include <XBOPTools_PaveBlockMapHasher.hxx>
#endif
#ifndef _XBOPTools_IndexedMapNodeOfIMapOfPaveBlock_HeaderFile
#include <XBOPTools_IndexedMapNodeOfIMapOfPaveBlock.hxx>
#endif
 

#define TheKey XBOPTools_PaveBlock
#define TheKey_hxx <XBOPTools_PaveBlock.hxx>
#define Hasher XBOPTools_PaveBlockMapHasher
#define Hasher_hxx <XBOPTools_PaveBlockMapHasher.hxx>
#define TCollection_IndexedMapNode XBOPTools_IndexedMapNodeOfIMapOfPaveBlock
#define TCollection_IndexedMapNode_hxx <XBOPTools_IndexedMapNodeOfIMapOfPaveBlock.hxx>
#define Handle_TCollection_IndexedMapNode Handle_XBOPTools_IndexedMapNodeOfIMapOfPaveBlock
#define TCollection_IndexedMapNode_Type_() XBOPTools_IndexedMapNodeOfIMapOfPaveBlock_Type_()
#define TCollection_IndexedMap XBOPTools_IMapOfPaveBlock
#define TCollection_IndexedMap_hxx <XBOPTools_IMapOfPaveBlock.hxx>
#include <TCollection_IndexedMap.gxx>

