// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_QuickSortPave.hxx>

#ifndef _XBOPTools_Pave_HeaderFile
#include <XBOPTools_Pave.hxx>
#endif
#ifndef _XBOPTools_Array1OfPave_HeaderFile
#include <XBOPTools_Array1OfPave.hxx>
#endif
#ifndef _XBOPTools_ComparePave_HeaderFile
#include <XBOPTools_ComparePave.hxx>
#endif
 

#define Item XBOPTools_Pave
#define Item_hxx <XBOPTools_Pave.hxx>
#define Array XBOPTools_Array1OfPave
#define Array_hxx <XBOPTools_Array1OfPave.hxx>
#define Comparator XBOPTools_ComparePave
#define Comparator_hxx <XBOPTools_ComparePave.hxx>
#define SortTools_QuickSort XBOPTools_QuickSortPave
#define SortTools_QuickSort_hxx <XBOPTools_QuickSortPave.hxx>
#include <SortTools_QuickSort.gxx>

