// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_HArray2OfIntersectionStatus.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_RangeError_HeaderFile
#include <Standard_RangeError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_OutOfMemory_HeaderFile
#include <Standard_OutOfMemory.hxx>
#endif
#ifndef _Standard_DimensionMismatch_HeaderFile
#include <Standard_DimensionMismatch.hxx>
#endif
#ifndef _XBOPTools_Array2OfIntersectionStatus_HeaderFile
#include <XBOPTools_Array2OfIntersectionStatus.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_HArray2OfIntersectionStatus)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_HArray2OfIntersectionStatus)


IMPLEMENT_DOWNCAST(XBOPTools_HArray2OfIntersectionStatus,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_HArray2OfIntersectionStatus)


#define ItemHArray2 XBOPTools_IntersectionStatus
#define ItemHArray2_hxx <XBOPTools_IntersectionStatus.hxx>
#define TheArray2 XBOPTools_Array2OfIntersectionStatus
#define TheArray2_hxx <XBOPTools_Array2OfIntersectionStatus.hxx>
#define TCollection_HArray2 XBOPTools_HArray2OfIntersectionStatus
#define TCollection_HArray2_hxx <XBOPTools_HArray2OfIntersectionStatus.hxx>
#define Handle_TCollection_HArray2 Handle_XBOPTools_HArray2OfIntersectionStatus
#define TCollection_HArray2_Type_() XBOPTools_HArray2OfIntersectionStatus_Type_()
#include <TCollection_HArray2.gxx>

