// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IDMapOfPaveBlockIMapOfInteger.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTools_PaveBlock_HeaderFile
#include <XBOPTools_PaveBlock.hxx>
#endif
#ifndef _TColStd_IndexedMapOfInteger_HeaderFile
#include <TColStd_IndexedMapOfInteger.hxx>
#endif
#ifndef _XBOPTools_PaveBlockMapHasher_HeaderFile
#include <XBOPTools_PaveBlockMapHasher.hxx>
#endif
#ifndef _XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfInteger_HeaderFile
#include <XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfInteger.hxx>
#endif
 

#define TheKey XBOPTools_PaveBlock
#define TheKey_hxx <XBOPTools_PaveBlock.hxx>
#define TheItem TColStd_IndexedMapOfInteger
#define TheItem_hxx <TColStd_IndexedMapOfInteger.hxx>
#define Hasher XBOPTools_PaveBlockMapHasher
#define Hasher_hxx <XBOPTools_PaveBlockMapHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfInteger
#define TCollection_IndexedDataMapNode_hxx <XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfInteger.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfInteger
#define TCollection_IndexedDataMapNode_Type_() XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfInteger_Type_()
#define TCollection_IndexedDataMap XBOPTools_IDMapOfPaveBlockIMapOfInteger
#define TCollection_IndexedDataMap_hxx <XBOPTools_IDMapOfPaveBlockIMapOfInteger.hxx>
#include <TCollection_IndexedDataMap.gxx>

