// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_Array2OfIntersectionStatus.hxx>

#ifndef _Standard_RangeError_HeaderFile
#include <Standard_RangeError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_OutOfMemory_HeaderFile
#include <Standard_OutOfMemory.hxx>
#endif
#ifndef _Standard_DimensionMismatch_HeaderFile
#include <Standard_DimensionMismatch.hxx>
#endif
 

#define Array2Item XBOPTools_IntersectionStatus
#define Array2Item_hxx <XBOPTools_IntersectionStatus.hxx>
#define TCollection_Array2 XBOPTools_Array2OfIntersectionStatus
#define TCollection_Array2_hxx <XBOPTools_Array2OfIntersectionStatus.hxx>
#include <TCollection_Array2.gxx>

