// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListOfShapeEnum.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTools_ListIteratorOfListOfShapeEnum_HeaderFile
#include <XBOPTools_ListIteratorOfListOfShapeEnum.hxx>
#endif
#ifndef _XBOPTools_ListNodeOfListOfShapeEnum_HeaderFile
#include <XBOPTools_ListNodeOfListOfShapeEnum.hxx>
#endif
 

#define Item TopAbs_ShapeEnum
#define Item_hxx <TopAbs_ShapeEnum.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfShapeEnum
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfShapeEnum.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfShapeEnum
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfShapeEnum.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfShapeEnum
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfShapeEnum_Type_()
#define TCollection_List XBOPTools_ListOfShapeEnum
#define TCollection_List_hxx <XBOPTools_ListOfShapeEnum.hxx>
#include <TCollection_List.gxx>

