// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IndexedDataMapOfShapeWithState.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _TopTools_ShapeMapHasher_HeaderFile
#include <TopTools_ShapeMapHasher.hxx>
#endif
#ifndef _XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState_HeaderFile
#include <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState.hxx>
#endif
 

#define TheKey TopoDS_Shape
#define TheKey_hxx <TopoDS_Shape.hxx>
#define TheItem XBooleanOperations_StateOfShape
#define TheItem_hxx <XBooleanOperations_StateOfShape.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <TopTools_ShapeMapHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState
#define TCollection_IndexedDataMapNode_hxx <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState
#define TCollection_IndexedDataMapNode_Type_() XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState_Type_()
#define TCollection_IndexedDataMap XBOPTools_IndexedDataMapOfShapeWithState
#define TCollection_IndexedDataMap_hxx <XBOPTools_IndexedDataMapOfShapeWithState.hxx>
#include <TCollection_IndexedDataMap.gxx>

