// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListNodeOfListOfCheckResults.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTools_CheckResult_HeaderFile
#include <XBOPTools_CheckResult.hxx>
#endif
#ifndef _XBOPTools_ListOfCheckResults_HeaderFile
#include <XBOPTools_ListOfCheckResults.hxx>
#endif
#ifndef _XBOPTools_ListIteratorOfListOfCheckResults_HeaderFile
#include <XBOPTools_ListIteratorOfListOfCheckResults.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_ListNodeOfListOfCheckResults)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_ListNodeOfListOfCheckResults)


IMPLEMENT_DOWNCAST(XBOPTools_ListNodeOfListOfCheckResults,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_ListNodeOfListOfCheckResults)


#define Item XBOPTools_CheckResult
#define Item_hxx <XBOPTools_CheckResult.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfCheckResults
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfCheckResults.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfCheckResults
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfCheckResults.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfCheckResults
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfCheckResults_Type_()
#define TCollection_List XBOPTools_ListOfCheckResults
#define TCollection_List_hxx <XBOPTools_ListOfCheckResults.hxx>
#include <TCollection_ListNode.gxx>

