// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerState.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _XBOPTools_IndexedDataMapOfIntegerState_HeaderFile
#include <XBOPTools_IndexedDataMapOfIntegerState.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerState)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerState)


IMPLEMENT_DOWNCAST(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerState,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerState)


#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem XBooleanOperations_StateOfShape
#define TheItem_hxx <XBooleanOperations_StateOfShape.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerState
#define TCollection_IndexedDataMapNode_hxx <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerState.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerState
#define TCollection_IndexedDataMapNode_Type_() XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerState_Type_()
#define TCollection_IndexedDataMap XBOPTools_IndexedDataMapOfIntegerState
#define TCollection_IndexedDataMap_hxx <XBOPTools_IndexedDataMapOfIntegerState.hxx>
#include <TCollection_IndexedDataMapNode.gxx>

