// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IndexedDataMapOfIntegerDEInfo.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTools_DEInfo_HeaderFile
#include <XBOPTools_DEInfo.hxx>
#endif
#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerDEInfo_HeaderFile
#include <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerDEInfo.hxx>
#endif
 

#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem XBOPTools_DEInfo
#define TheItem_hxx <XBOPTools_DEInfo.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerDEInfo
#define TCollection_IndexedDataMapNode_hxx <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerDEInfo.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerDEInfo
#define TCollection_IndexedDataMapNode_Type_() XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerDEInfo_Type_()
#define TCollection_IndexedDataMap XBOPTools_IndexedDataMapOfIntegerDEInfo
#define TCollection_IndexedDataMap_hxx <XBOPTools_IndexedDataMapOfIntegerDEInfo.hxx>
#include <TCollection_IndexedDataMap.gxx>

