// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListNodeOfListOfShapeEnum.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTools_ListOfShapeEnum_HeaderFile
#include <XBOPTools_ListOfShapeEnum.hxx>
#endif
#ifndef _XBOPTools_ListIteratorOfListOfShapeEnum_HeaderFile
#include <XBOPTools_ListIteratorOfListOfShapeEnum.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_ListNodeOfListOfShapeEnum)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_ListNodeOfListOfShapeEnum)


IMPLEMENT_DOWNCAST(XBOPTools_ListNodeOfListOfShapeEnum,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_ListNodeOfListOfShapeEnum)


#define Item TopAbs_ShapeEnum
#define Item_hxx <TopAbs_ShapeEnum.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfShapeEnum
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfShapeEnum.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfShapeEnum
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfShapeEnum.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfShapeEnum
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfShapeEnum_Type_()
#define TCollection_List XBOPTools_ListOfShapeEnum
#define TCollection_List_hxx <XBOPTools_ListOfShapeEnum.hxx>
#include <TCollection_ListNode.gxx>

