// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_SequenceNodeOfSequenceOfCurves.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTools_Curve_HeaderFile
#include <XBOPTools_Curve.hxx>
#endif
#ifndef _XBOPTools_SequenceOfCurves_HeaderFile
#include <XBOPTools_SequenceOfCurves.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_SequenceNodeOfSequenceOfCurves)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_SequenceNodeOfSequenceOfCurves)


IMPLEMENT_DOWNCAST(XBOPTools_SequenceNodeOfSequenceOfCurves,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_SequenceNodeOfSequenceOfCurves)


#define SeqItem XBOPTools_Curve
#define SeqItem_hxx <XBOPTools_Curve.hxx>
#define TCollection_SequenceNode XBOPTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_hxx <XBOPTools_SequenceNodeOfSequenceOfCurves.hxx>
#define Handle_TCollection_SequenceNode Handle_XBOPTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_Type_() XBOPTools_SequenceNodeOfSequenceOfCurves_Type_()
#define TCollection_Sequence XBOPTools_SequenceOfCurves
#define TCollection_Sequence_hxx <XBOPTools_SequenceOfCurves.hxx>
#include <TCollection_SequenceNode.gxx>

