// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListNodeOfListOfCoupleOfInteger.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTools_CoupleOfInteger_HeaderFile
#include <XBOPTools_CoupleOfInteger.hxx>
#endif
#ifndef _XBOPTools_ListOfCoupleOfInteger_HeaderFile
#include <XBOPTools_ListOfCoupleOfInteger.hxx>
#endif
#ifndef _XBOPTools_ListIteratorOfListOfCoupleOfInteger_HeaderFile
#include <XBOPTools_ListIteratorOfListOfCoupleOfInteger.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_ListNodeOfListOfCoupleOfInteger)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_ListNodeOfListOfCoupleOfInteger)


IMPLEMENT_DOWNCAST(XBOPTools_ListNodeOfListOfCoupleOfInteger,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_ListNodeOfListOfCoupleOfInteger)


#define Item XBOPTools_CoupleOfInteger
#define Item_hxx <XBOPTools_CoupleOfInteger.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfCoupleOfInteger
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfCoupleOfInteger.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfCoupleOfInteger
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfCoupleOfInteger.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfCoupleOfInteger
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfCoupleOfInteger_Type_()
#define TCollection_List XBOPTools_ListOfCoupleOfInteger
#define TCollection_List_hxx <XBOPTools_ListOfCoupleOfInteger.hxx>
#include <TCollection_ListNode.gxx>

