// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _TopTools_ShapeMapHasher_HeaderFile
#include <TopTools_ShapeMapHasher.hxx>
#endif
#ifndef _XBOPTools_IndexedDataMapOfShapeWithState_HeaderFile
#include <XBOPTools_IndexedDataMapOfShapeWithState.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState)


IMPLEMENT_DOWNCAST(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState)


#define TheKey TopoDS_Shape
#define TheKey_hxx <TopoDS_Shape.hxx>
#define TheItem XBooleanOperations_StateOfShape
#define TheItem_hxx <XBooleanOperations_StateOfShape.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <TopTools_ShapeMapHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState
#define TCollection_IndexedDataMapNode_hxx <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState
#define TCollection_IndexedDataMapNode_Type_() XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfShapeWithState_Type_()
#define TCollection_IndexedDataMap XBOPTools_IndexedDataMapOfShapeWithState
#define TCollection_IndexedDataMap_hxx <XBOPTools_IndexedDataMapOfShapeWithState.hxx>
#include <TCollection_IndexedDataMapNode.gxx>

