// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTools_PaveBlock_HeaderFile
#include <XBOPTools_PaveBlock.hxx>
#endif
#ifndef _XBOPTools_IMapOfPaveBlock_HeaderFile
#include <XBOPTools_IMapOfPaveBlock.hxx>
#endif
#ifndef _XBOPTools_PaveBlockMapHasher_HeaderFile
#include <XBOPTools_PaveBlockMapHasher.hxx>
#endif
#ifndef _XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock_HeaderFile
#include <XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock.hxx>
#endif
 

#define TheKey XBOPTools_PaveBlock
#define TheKey_hxx <XBOPTools_PaveBlock.hxx>
#define TheItem XBOPTools_IMapOfPaveBlock
#define TheItem_hxx <XBOPTools_IMapOfPaveBlock.hxx>
#define Hasher XBOPTools_PaveBlockMapHasher
#define Hasher_hxx <XBOPTools_PaveBlockMapHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock
#define TCollection_IndexedDataMapNode_hxx <XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock
#define TCollection_IndexedDataMapNode_Type_() XBOPTools_IndexedDataMapNodeOfIDMapOfPaveBlockIMapOfPaveBlock_Type_()
#define TCollection_IndexedDataMap XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock
#define TCollection_IndexedDataMap_hxx <XBOPTools_IDMapOfPaveBlockIMapOfPaveBlock.hxx>
#include <TCollection_IndexedDataMap.gxx>

