// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListIteratorOfListOfPave.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTools_ListOfPave_HeaderFile
#include <XBOPTools_ListOfPave.hxx>
#endif
#ifndef _XBOPTools_Pave_HeaderFile
#include <XBOPTools_Pave.hxx>
#endif
#ifndef _XBOPTools_ListNodeOfListOfPave_HeaderFile
#include <XBOPTools_ListNodeOfListOfPave.hxx>
#endif
 

#define Item XBOPTools_Pave
#define Item_hxx <XBOPTools_Pave.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfPave
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfPave.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfPave
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfPave.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfPave
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfPave_Type_()
#define TCollection_List XBOPTools_ListOfPave
#define TCollection_List_hxx <XBOPTools_ListOfPave.hxx>
#include <TCollection_ListIterator.gxx>

