// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IndexedMapNodeOfIMapOfPaveBlock.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTools_PaveBlock_HeaderFile
#include <XBOPTools_PaveBlock.hxx>
#endif
#ifndef _XBOPTools_PaveBlockMapHasher_HeaderFile
#include <XBOPTools_PaveBlockMapHasher.hxx>
#endif
#ifndef _XBOPTools_IMapOfPaveBlock_HeaderFile
#include <XBOPTools_IMapOfPaveBlock.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_IndexedMapNodeOfIMapOfPaveBlock)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_IndexedMapNodeOfIMapOfPaveBlock)


IMPLEMENT_DOWNCAST(XBOPTools_IndexedMapNodeOfIMapOfPaveBlock,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_IndexedMapNodeOfIMapOfPaveBlock)


#define TheKey XBOPTools_PaveBlock
#define TheKey_hxx <XBOPTools_PaveBlock.hxx>
#define Hasher XBOPTools_PaveBlockMapHasher
#define Hasher_hxx <XBOPTools_PaveBlockMapHasher.hxx>
#define TCollection_IndexedMapNode XBOPTools_IndexedMapNodeOfIMapOfPaveBlock
#define TCollection_IndexedMapNode_hxx <XBOPTools_IndexedMapNodeOfIMapOfPaveBlock.hxx>
#define Handle_TCollection_IndexedMapNode Handle_XBOPTools_IndexedMapNodeOfIMapOfPaveBlock
#define TCollection_IndexedMapNode_Type_() XBOPTools_IndexedMapNodeOfIMapOfPaveBlock_Type_()
#define TCollection_IndexedMap XBOPTools_IMapOfPaveBlock
#define TCollection_IndexedMap_hxx <XBOPTools_IMapOfPaveBlock.hxx>
#include <TCollection_IndexedMapNode.gxx>

