// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_SequenceOfCurves.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _XBOPTools_Curve_HeaderFile
#include <XBOPTools_Curve.hxx>
#endif
#ifndef _XBOPTools_SequenceNodeOfSequenceOfCurves_HeaderFile
#include <XBOPTools_SequenceNodeOfSequenceOfCurves.hxx>
#endif
 

#define SeqItem XBOPTools_Curve
#define SeqItem_hxx <XBOPTools_Curve.hxx>
#define TCollection_SequenceNode XBOPTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_hxx <XBOPTools_SequenceNodeOfSequenceOfCurves.hxx>
#define Handle_TCollection_SequenceNode Handle_XBOPTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_Type_() XBOPTools_SequenceNodeOfSequenceOfCurves_Type_()
#define TCollection_Sequence XBOPTools_SequenceOfCurves
#define TCollection_Sequence_hxx <XBOPTools_SequenceOfCurves.hxx>
#include <TCollection_Sequence.gxx>

