// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListIteratorOfListOfInterference.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTools_ListOfInterference_HeaderFile
#include <XBOPTools_ListOfInterference.hxx>
#endif
#ifndef _XBOPTools_Interference_HeaderFile
#include <XBOPTools_Interference.hxx>
#endif
#ifndef _XBOPTools_ListNodeOfListOfInterference_HeaderFile
#include <XBOPTools_ListNodeOfListOfInterference.hxx>
#endif
 

#define Item XBOPTools_Interference
#define Item_hxx <XBOPTools_Interference.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfInterference
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfInterference.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfInterference
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfInterference.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfInterference
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfInterference_Type_()
#define TCollection_List XBOPTools_ListOfInterference
#define TCollection_List_hxx <XBOPTools_ListOfInterference.hxx>
#include <TCollection_ListIterator.gxx>

