// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IndexedMapOfCoupleOfInteger.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _XBOPTools_CoupleOfInteger_HeaderFile
#include <XBOPTools_CoupleOfInteger.hxx>
#endif
#ifndef _XBOPTools_CoupleOfIntegerMapHasher_HeaderFile
#include <XBOPTools_CoupleOfIntegerMapHasher.hxx>
#endif
#ifndef _XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger_HeaderFile
#include <XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger.hxx>
#endif
 

#define TheKey XBOPTools_CoupleOfInteger
#define TheKey_hxx <XBOPTools_CoupleOfInteger.hxx>
#define Hasher XBOPTools_CoupleOfIntegerMapHasher
#define Hasher_hxx <XBOPTools_CoupleOfIntegerMapHasher.hxx>
#define TCollection_IndexedMapNode XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger
#define TCollection_IndexedMapNode_hxx <XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger.hxx>
#define Handle_TCollection_IndexedMapNode Handle_XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger
#define TCollection_IndexedMapNode_Type_() XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger_Type_()
#define TCollection_IndexedMap XBOPTools_IndexedMapOfCoupleOfInteger
#define TCollection_IndexedMap_hxx <XBOPTools_IndexedMapOfCoupleOfInteger.hxx>
#include <TCollection_IndexedMap.gxx>

