// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_SequenceOfPaveBlock.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _XBOPTools_PaveBlock_HeaderFile
#include <XBOPTools_PaveBlock.hxx>
#endif
#ifndef _XBOPTools_SequenceNodeOfSequenceOfPaveBlock_HeaderFile
#include <XBOPTools_SequenceNodeOfSequenceOfPaveBlock.hxx>
#endif
 

#define SeqItem XBOPTools_PaveBlock
#define SeqItem_hxx <XBOPTools_PaveBlock.hxx>
#define TCollection_SequenceNode XBOPTools_SequenceNodeOfSequenceOfPaveBlock
#define TCollection_SequenceNode_hxx <XBOPTools_SequenceNodeOfSequenceOfPaveBlock.hxx>
#define Handle_TCollection_SequenceNode Handle_XBOPTools_SequenceNodeOfSequenceOfPaveBlock
#define TCollection_SequenceNode_Type_() XBOPTools_SequenceNodeOfSequenceOfPaveBlock_Type_()
#define TCollection_Sequence XBOPTools_SequenceOfPaveBlock
#define TCollection_Sequence_hxx <XBOPTools_SequenceOfPaveBlock.hxx>
#include <TCollection_Sequence.gxx>

