// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListOfCommonBlock.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTools_ListIteratorOfListOfCommonBlock_HeaderFile
#include <XBOPTools_ListIteratorOfListOfCommonBlock.hxx>
#endif
#ifndef _XBOPTools_CommonBlock_HeaderFile
#include <XBOPTools_CommonBlock.hxx>
#endif
#ifndef _XBOPTools_ListNodeOfListOfCommonBlock_HeaderFile
#include <XBOPTools_ListNodeOfListOfCommonBlock.hxx>
#endif
 

#define Item XBOPTools_CommonBlock
#define Item_hxx <XBOPTools_CommonBlock.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfCommonBlock
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfCommonBlock.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfCommonBlock
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfCommonBlock.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfCommonBlock
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfCommonBlock_Type_()
#define TCollection_List XBOPTools_ListOfCommonBlock
#define TCollection_List_hxx <XBOPTools_ListOfCommonBlock.hxx>
#include <TCollection_List.gxx>

