// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListNodeOfListOfInterference.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTools_Interference_HeaderFile
#include <XBOPTools_Interference.hxx>
#endif
#ifndef _XBOPTools_ListOfInterference_HeaderFile
#include <XBOPTools_ListOfInterference.hxx>
#endif
#ifndef _XBOPTools_ListIteratorOfListOfInterference_HeaderFile
#include <XBOPTools_ListIteratorOfListOfInterference.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_ListNodeOfListOfInterference)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_ListNodeOfListOfInterference)


IMPLEMENT_DOWNCAST(XBOPTools_ListNodeOfListOfInterference,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_ListNodeOfListOfInterference)


#define Item XBOPTools_Interference
#define Item_hxx <XBOPTools_Interference.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfInterference
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfInterference.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfInterference
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfInterference.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfInterference
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfInterference_Type_()
#define TCollection_List XBOPTools_ListOfInterference
#define TCollection_List_hxx <XBOPTools_ListOfInterference.hxx>
#include <TCollection_ListNode.gxx>

