// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTools_CoupleOfInteger_HeaderFile
#include <XBOPTools_CoupleOfInteger.hxx>
#endif
#ifndef _XBOPTools_CoupleOfIntegerMapHasher_HeaderFile
#include <XBOPTools_CoupleOfIntegerMapHasher.hxx>
#endif
#ifndef _XBOPTools_IndexedMapOfCoupleOfInteger_HeaderFile
#include <XBOPTools_IndexedMapOfCoupleOfInteger.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger)


IMPLEMENT_DOWNCAST(XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger)


#define TheKey XBOPTools_CoupleOfInteger
#define TheKey_hxx <XBOPTools_CoupleOfInteger.hxx>
#define Hasher XBOPTools_CoupleOfIntegerMapHasher
#define Hasher_hxx <XBOPTools_CoupleOfIntegerMapHasher.hxx>
#define TCollection_IndexedMapNode XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger
#define TCollection_IndexedMapNode_hxx <XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger.hxx>
#define Handle_TCollection_IndexedMapNode Handle_XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger
#define TCollection_IndexedMapNode_Type_() XBOPTools_IndexedMapNodeOfIndexedMapOfCoupleOfInteger_Type_()
#define TCollection_IndexedMap XBOPTools_IndexedMapOfCoupleOfInteger
#define TCollection_IndexedMap_hxx <XBOPTools_IndexedMapOfCoupleOfInteger.hxx>
#include <TCollection_IndexedMapNode.gxx>

