// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_SplitShapesPool.hxx>

#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_OutOfMemory_HeaderFile
#include <Standard_OutOfMemory.hxx>
#endif
#ifndef _XBOPTools_ListOfPaveBlock_HeaderFile
#include <XBOPTools_ListOfPaveBlock.hxx>
#endif
 

#define Array1Item XBOPTools_ListOfPaveBlock
#define Array1Item_hxx <XBOPTools_ListOfPaveBlock.hxx>
#define XBOPTColStd_CArray1 XBOPTools_SplitShapesPool
#define XBOPTColStd_CArray1_hxx <XBOPTools_SplitShapesPool.hxx>
#include <XBOPTColStd_CArray1.gxx>

