// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListIteratorOfListOfPaveBlock.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTools_ListOfPaveBlock_HeaderFile
#include <XBOPTools_ListOfPaveBlock.hxx>
#endif
#ifndef _XBOPTools_PaveBlock_HeaderFile
#include <XBOPTools_PaveBlock.hxx>
#endif
#ifndef _XBOPTools_ListNodeOfListOfPaveBlock_HeaderFile
#include <XBOPTools_ListNodeOfListOfPaveBlock.hxx>
#endif
 

#define Item XBOPTools_PaveBlock
#define Item_hxx <XBOPTools_PaveBlock.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfPaveBlock
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfPaveBlock.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfPaveBlock
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfPaveBlock.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfPaveBlock
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfPaveBlock_Type_()
#define TCollection_List XBOPTools_ListOfPaveBlock
#define TCollection_List_hxx <XBOPTools_ListOfPaveBlock.hxx>
#include <TCollection_ListIterator.gxx>

