// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTools_PaveSet_HeaderFile
#include <XBOPTools_PaveSet.hxx>
#endif
#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _XBOPTools_IndexedDataMapOfIntegerPaveSet_HeaderFile
#include <XBOPTools_IndexedDataMapOfIntegerPaveSet.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet)


IMPLEMENT_DOWNCAST(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet)


#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem XBOPTools_PaveSet
#define TheItem_hxx <XBOPTools_PaveSet.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet
#define TCollection_IndexedDataMapNode_hxx <XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet
#define TCollection_IndexedDataMapNode_Type_() XBOPTools_IndexedDataMapNodeOfIndexedDataMapOfIntegerPaveSet_Type_()
#define TCollection_IndexedDataMap XBOPTools_IndexedDataMapOfIntegerPaveSet
#define TCollection_IndexedDataMap_hxx <XBOPTools_IndexedDataMapOfIntegerPaveSet.hxx>
#include <TCollection_IndexedDataMapNode.gxx>

