// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListNodeOfListOfPave.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTools_Pave_HeaderFile
#include <XBOPTools_Pave.hxx>
#endif
#ifndef _XBOPTools_ListOfPave_HeaderFile
#include <XBOPTools_ListOfPave.hxx>
#endif
#ifndef _XBOPTools_ListIteratorOfListOfPave_HeaderFile
#include <XBOPTools_ListIteratorOfListOfPave.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTools_ListNodeOfListOfPave)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTools_ListNodeOfListOfPave)


IMPLEMENT_DOWNCAST(XBOPTools_ListNodeOfListOfPave,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTools_ListNodeOfListOfPave)


#define Item XBOPTools_Pave
#define Item_hxx <XBOPTools_Pave.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfPave
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfPave.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfPave
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfPave.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfPave
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfPave_Type_()
#define TCollection_List XBOPTools_ListOfPave
#define TCollection_List_hxx <XBOPTools_ListOfPave.hxx>
#include <TCollection_ListNode.gxx>

