// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_ListIteratorOfListOfCheckResults.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTools_ListOfCheckResults_HeaderFile
#include <XBOPTools_ListOfCheckResults.hxx>
#endif
#ifndef _XBOPTools_CheckResult_HeaderFile
#include <XBOPTools_CheckResult.hxx>
#endif
#ifndef _XBOPTools_ListNodeOfListOfCheckResults_HeaderFile
#include <XBOPTools_ListNodeOfListOfCheckResults.hxx>
#endif
 

#define Item XBOPTools_CheckResult
#define Item_hxx <XBOPTools_CheckResult.hxx>
#define TCollection_ListNode XBOPTools_ListNodeOfListOfCheckResults
#define TCollection_ListNode_hxx <XBOPTools_ListNodeOfListOfCheckResults.hxx>
#define TCollection_ListIterator XBOPTools_ListIteratorOfListOfCheckResults
#define TCollection_ListIterator_hxx <XBOPTools_ListIteratorOfListOfCheckResults.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTools_ListNodeOfListOfCheckResults
#define TCollection_ListNode_Type_() XBOPTools_ListNodeOfListOfCheckResults_Type_()
#define TCollection_List XBOPTools_ListOfCheckResults
#define TCollection_List_hxx <XBOPTools_ListOfCheckResults.hxx>
#include <TCollection_ListIterator.gxx>

