// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTools_Array1OfPave.hxx>

#ifndef _Standard_RangeError_HeaderFile
#include <Standard_RangeError.hxx>
#endif
#ifndef _Standard_DimensionMismatch_HeaderFile
#include <Standard_DimensionMismatch.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_OutOfMemory_HeaderFile
#include <Standard_OutOfMemory.hxx>
#endif
#ifndef _XBOPTools_Pave_HeaderFile
#include <XBOPTools_Pave.hxx>
#endif
 

#define Array1Item XBOPTools_Pave
#define Array1Item_hxx <XBOPTools_Pave.hxx>
#define TCollection_Array1 XBOPTools_Array1OfPave
#define TCollection_Array1_hxx <XBOPTools_Array1OfPave.hxx>
#include <TCollection_Array1.gxx>

