// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfIntegerInteger.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _TColStd_MapIntegerHasher_HeaderFile
#include <TColStd_MapIntegerHasher.hxx>
#endif
#ifndef _XBOPTColStd_IndexedDataMapOfIntegerInteger_HeaderFile
#include <XBOPTColStd_IndexedDataMapOfIntegerInteger.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfIntegerInteger)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfIntegerInteger)


IMPLEMENT_DOWNCAST(XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfIntegerInteger,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfIntegerInteger)


#define TheKey Standard_Integer
#define TheKey_hxx <Standard_Integer.hxx>
#define TheItem Standard_Integer
#define TheItem_hxx <Standard_Integer.hxx>
#define Hasher TColStd_MapIntegerHasher
#define Hasher_hxx <TColStd_MapIntegerHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfIntegerInteger
#define TCollection_IndexedDataMapNode_hxx <XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfIntegerInteger.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfIntegerInteger
#define TCollection_IndexedDataMapNode_Type_() XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfIntegerInteger_Type_()
#define TCollection_IndexedDataMap XBOPTColStd_IndexedDataMapOfIntegerInteger
#define TCollection_IndexedDataMap_hxx <XBOPTColStd_IndexedDataMapOfIntegerInteger.hxx>
#include <TCollection_IndexedDataMapNode.gxx>

