// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTColStd_IndexedDataMapOfSWRInteger.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTColStd_ShapeWithRank_HeaderFile
#include <XBOPTColStd_ShapeWithRank.hxx>
#endif
#ifndef _XBOPTColStd_ShapeWithRankHasher_HeaderFile
#include <XBOPTColStd_ShapeWithRankHasher.hxx>
#endif
#ifndef _XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger_HeaderFile
#include <XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger.hxx>
#endif
 

#define TheKey XBOPTColStd_ShapeWithRank
#define TheKey_hxx <XBOPTColStd_ShapeWithRank.hxx>
#define TheItem Standard_Integer
#define TheItem_hxx <Standard_Integer.hxx>
#define Hasher XBOPTColStd_ShapeWithRankHasher
#define Hasher_hxx <XBOPTColStd_ShapeWithRankHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger
#define TCollection_IndexedDataMapNode_hxx <XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger
#define TCollection_IndexedDataMapNode_Type_() XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger_Type_()
#define TCollection_IndexedDataMap XBOPTColStd_IndexedDataMapOfSWRInteger
#define TCollection_IndexedDataMap_hxx <XBOPTColStd_IndexedDataMapOfSWRInteger.hxx>
#include <TCollection_IndexedDataMap.gxx>

