// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOPTColStd_ShapeWithRank_HeaderFile
#include <XBOPTColStd_ShapeWithRank.hxx>
#endif
#ifndef _XBOPTColStd_ShapeWithRankHasher_HeaderFile
#include <XBOPTColStd_ShapeWithRankHasher.hxx>
#endif
#ifndef _XBOPTColStd_IndexedDataMapOfSWRInteger_HeaderFile
#include <XBOPTColStd_IndexedDataMapOfSWRInteger.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger)


IMPLEMENT_DOWNCAST(XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger)


#define TheKey XBOPTColStd_ShapeWithRank
#define TheKey_hxx <XBOPTColStd_ShapeWithRank.hxx>
#define TheItem Standard_Integer
#define TheItem_hxx <Standard_Integer.hxx>
#define Hasher XBOPTColStd_ShapeWithRankHasher
#define Hasher_hxx <XBOPTColStd_ShapeWithRankHasher.hxx>
#define TCollection_IndexedDataMapNode XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger
#define TCollection_IndexedDataMapNode_hxx <XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger
#define TCollection_IndexedDataMapNode_Type_() XBOPTColStd_IndexedDataMapNodeOfIndexedDataMapOfSWRInteger_Type_()
#define TCollection_IndexedDataMap XBOPTColStd_IndexedDataMapOfSWRInteger
#define TCollection_IndexedDataMap_hxx <XBOPTColStd_IndexedDataMapOfSWRInteger.hxx>
#include <TCollection_IndexedDataMapNode.gxx>

