// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOPTColStd_ListOfListOfShape.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOPTColStd_ListIteratorOfListOfListOfShape_HeaderFile
#include <XBOPTColStd_ListIteratorOfListOfListOfShape.hxx>
#endif
#ifndef _TopTools_ListOfShape_HeaderFile
#include <TopTools_ListOfShape.hxx>
#endif
#ifndef _XBOPTColStd_ListNodeOfListOfListOfShape_HeaderFile
#include <XBOPTColStd_ListNodeOfListOfListOfShape.hxx>
#endif
 

#define Item TopTools_ListOfShape
#define Item_hxx <TopTools_ListOfShape.hxx>
#define TCollection_ListNode XBOPTColStd_ListNodeOfListOfListOfShape
#define TCollection_ListNode_hxx <XBOPTColStd_ListNodeOfListOfListOfShape.hxx>
#define TCollection_ListIterator XBOPTColStd_ListIteratorOfListOfListOfShape
#define TCollection_ListIterator_hxx <XBOPTColStd_ListIteratorOfListOfListOfShape.hxx>
#define Handle_TCollection_ListNode Handle_XBOPTColStd_ListNodeOfListOfListOfShape
#define TCollection_ListNode_Type_() XBOPTColStd_ListNodeOfListOfListOfShape_Type_()
#define TCollection_List XBOPTColStd_ListOfListOfShape
#define TCollection_List_hxx <XBOPTColStd_ListOfListOfShape.hxx>
#include <TCollection_List.gxx>

