// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_ListNodeOfListOfBox.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Bnd_Box_HeaderFile
#include <Bnd_Box.hxx>
#endif
#ifndef _XIntTools_ListOfBox_HeaderFile
#include <XIntTools_ListOfBox.hxx>
#endif
#ifndef _XIntTools_ListIteratorOfListOfBox_HeaderFile
#include <XIntTools_ListIteratorOfListOfBox.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XIntTools_ListNodeOfListOfBox)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XIntTools_ListNodeOfListOfBox)


IMPLEMENT_DOWNCAST(XIntTools_ListNodeOfListOfBox,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XIntTools_ListNodeOfListOfBox)


#define Item Bnd_Box
#define Item_hxx <Bnd_Box.hxx>
#define TCollection_ListNode XIntTools_ListNodeOfListOfBox
#define TCollection_ListNode_hxx <XIntTools_ListNodeOfListOfBox.hxx>
#define TCollection_ListIterator XIntTools_ListIteratorOfListOfBox
#define TCollection_ListIterator_hxx <XIntTools_ListIteratorOfListOfBox.hxx>
#define Handle_TCollection_ListNode Handle_XIntTools_ListNodeOfListOfBox
#define TCollection_ListNode_Type_() XIntTools_ListNodeOfListOfBox_Type_()
#define TCollection_List XIntTools_ListOfBox
#define TCollection_List_hxx <XIntTools_ListOfBox.hxx>
#include <TCollection_ListNode.gxx>

