// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_SequenceOfRoots.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _XIntTools_Root_HeaderFile
#include <XIntTools_Root.hxx>
#endif
#ifndef _XIntTools_SequenceNodeOfSequenceOfRoots_HeaderFile
#include <XIntTools_SequenceNodeOfSequenceOfRoots.hxx>
#endif
 

#define SeqItem XIntTools_Root
#define SeqItem_hxx <XIntTools_Root.hxx>
#define TCollection_SequenceNode XIntTools_SequenceNodeOfSequenceOfRoots
#define TCollection_SequenceNode_hxx <XIntTools_SequenceNodeOfSequenceOfRoots.hxx>
#define Handle_TCollection_SequenceNode Handle_XIntTools_SequenceNodeOfSequenceOfRoots
#define TCollection_SequenceNode_Type_() XIntTools_SequenceNodeOfSequenceOfRoots_Type_()
#define TCollection_Sequence XIntTools_SequenceOfRoots
#define TCollection_Sequence_hxx <XIntTools_SequenceOfRoots.hxx>
#include <TCollection_Sequence.gxx>

