// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_MapOfSurfaceSample.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _XIntTools_SurfaceRangeSample_HeaderFile
#include <XIntTools_SurfaceRangeSample.hxx>
#endif
#ifndef _XIntTools_SurfaceRangeSampleMapHasher_HeaderFile
#include <XIntTools_SurfaceRangeSampleMapHasher.hxx>
#endif
#ifndef _XIntTools_StdMapNodeOfMapOfSurfaceSample_HeaderFile
#include <XIntTools_StdMapNodeOfMapOfSurfaceSample.hxx>
#endif
#ifndef _XIntTools_MapIteratorOfMapOfSurfaceSample_HeaderFile
#include <XIntTools_MapIteratorOfMapOfSurfaceSample.hxx>
#endif
 

#define TheKey XIntTools_SurfaceRangeSample
#define TheKey_hxx <XIntTools_SurfaceRangeSample.hxx>
#define Hasher XIntTools_SurfaceRangeSampleMapHasher
#define Hasher_hxx <XIntTools_SurfaceRangeSampleMapHasher.hxx>
#define TCollection_StdMapNode XIntTools_StdMapNodeOfMapOfSurfaceSample
#define TCollection_StdMapNode_hxx <XIntTools_StdMapNodeOfMapOfSurfaceSample.hxx>
#define TCollection_MapIterator XIntTools_MapIteratorOfMapOfSurfaceSample
#define TCollection_MapIterator_hxx <XIntTools_MapIteratorOfMapOfSurfaceSample.hxx>
#define Handle_TCollection_StdMapNode Handle_XIntTools_StdMapNodeOfMapOfSurfaceSample
#define TCollection_StdMapNode_Type_() XIntTools_StdMapNodeOfMapOfSurfaceSample_Type_()
#define TCollection_Map XIntTools_MapOfSurfaceSample
#define TCollection_Map_hxx <XIntTools_MapOfSurfaceSample.hxx>
#include <TCollection_Map.gxx>

