// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_SequenceOfCurves.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _XIntTools_Curve_HeaderFile
#include <XIntTools_Curve.hxx>
#endif
#ifndef _XIntTools_SequenceNodeOfSequenceOfCurves_HeaderFile
#include <XIntTools_SequenceNodeOfSequenceOfCurves.hxx>
#endif
 

#define SeqItem XIntTools_Curve
#define SeqItem_hxx <XIntTools_Curve.hxx>
#define TCollection_SequenceNode XIntTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_hxx <XIntTools_SequenceNodeOfSequenceOfCurves.hxx>
#define Handle_TCollection_SequenceNode Handle_XIntTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_Type_() XIntTools_SequenceNodeOfSequenceOfCurves_Type_()
#define TCollection_Sequence XIntTools_SequenceOfCurves
#define TCollection_Sequence_hxx <XIntTools_SequenceOfCurves.hxx>
#include <TCollection_Sequence.gxx>

