// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_QuickSort.hxx>

#ifndef _XIntTools_Root_HeaderFile
#include <XIntTools_Root.hxx>
#endif
#ifndef _XIntTools_Array1OfRoots_HeaderFile
#include <XIntTools_Array1OfRoots.hxx>
#endif
#ifndef _XIntTools_Compare_HeaderFile
#include <XIntTools_Compare.hxx>
#endif
 

#define Item XIntTools_Root
#define Item_hxx <XIntTools_Root.hxx>
#define Array XIntTools_Array1OfRoots
#define Array_hxx <XIntTools_Array1OfRoots.hxx>
#define Comparator XIntTools_Compare
#define Comparator_hxx <XIntTools_Compare.hxx>
#define SortTools_QuickSort XIntTools_QuickSort
#define SortTools_QuickSort_hxx <XIntTools_QuickSort.hxx>
#include <SortTools_QuickSort.gxx>

