// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_SequenceNodeOfSequenceOfPntOn2Faces.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XIntTools_PntOn2Faces_HeaderFile
#include <XIntTools_PntOn2Faces.hxx>
#endif
#ifndef _XIntTools_SequenceOfPntOn2Faces_HeaderFile
#include <XIntTools_SequenceOfPntOn2Faces.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XIntTools_SequenceNodeOfSequenceOfPntOn2Faces)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XIntTools_SequenceNodeOfSequenceOfPntOn2Faces)


IMPLEMENT_DOWNCAST(XIntTools_SequenceNodeOfSequenceOfPntOn2Faces,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XIntTools_SequenceNodeOfSequenceOfPntOn2Faces)


#define SeqItem XIntTools_PntOn2Faces
#define SeqItem_hxx <XIntTools_PntOn2Faces.hxx>
#define TCollection_SequenceNode XIntTools_SequenceNodeOfSequenceOfPntOn2Faces
#define TCollection_SequenceNode_hxx <XIntTools_SequenceNodeOfSequenceOfPntOn2Faces.hxx>
#define Handle_TCollection_SequenceNode Handle_XIntTools_SequenceNodeOfSequenceOfPntOn2Faces
#define TCollection_SequenceNode_Type_() XIntTools_SequenceNodeOfSequenceOfPntOn2Faces_Type_()
#define TCollection_Sequence XIntTools_SequenceOfPntOn2Faces
#define TCollection_Sequence_hxx <XIntTools_SequenceOfPntOn2Faces.hxx>
#include <TCollection_SequenceNode.gxx>

