// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_Array1OfRoots.hxx>

#ifndef _Standard_RangeError_HeaderFile
#include <Standard_RangeError.hxx>
#endif
#ifndef _Standard_DimensionMismatch_HeaderFile
#include <Standard_DimensionMismatch.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_OutOfMemory_HeaderFile
#include <Standard_OutOfMemory.hxx>
#endif
#ifndef _XIntTools_Root_HeaderFile
#include <XIntTools_Root.hxx>
#endif
 

#define Array1Item XIntTools_Root
#define Array1Item_hxx <XIntTools_Root.hxx>
#define TCollection_Array1 XIntTools_Array1OfRoots
#define TCollection_Array1_hxx <XIntTools_Array1OfRoots.hxx>
#include <TCollection_Array1.gxx>

