// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_SequenceNodeOfSequenceOfRoots.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XIntTools_Root_HeaderFile
#include <XIntTools_Root.hxx>
#endif
#ifndef _XIntTools_SequenceOfRoots_HeaderFile
#include <XIntTools_SequenceOfRoots.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XIntTools_SequenceNodeOfSequenceOfRoots)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XIntTools_SequenceNodeOfSequenceOfRoots)


IMPLEMENT_DOWNCAST(XIntTools_SequenceNodeOfSequenceOfRoots,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XIntTools_SequenceNodeOfSequenceOfRoots)


#define SeqItem XIntTools_Root
#define SeqItem_hxx <XIntTools_Root.hxx>
#define TCollection_SequenceNode XIntTools_SequenceNodeOfSequenceOfRoots
#define TCollection_SequenceNode_hxx <XIntTools_SequenceNodeOfSequenceOfRoots.hxx>
#define Handle_TCollection_SequenceNode Handle_XIntTools_SequenceNodeOfSequenceOfRoots
#define TCollection_SequenceNode_Type_() XIntTools_SequenceNodeOfSequenceOfRoots_Type_()
#define TCollection_Sequence XIntTools_SequenceOfRoots
#define TCollection_Sequence_hxx <XIntTools_SequenceOfRoots.hxx>
#include <TCollection_SequenceNode.gxx>

