// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_DataMapIteratorOfDataMapOfSurfaceSampleBox.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XIntTools_SurfaceRangeSample_HeaderFile
#include <XIntTools_SurfaceRangeSample.hxx>
#endif
#ifndef _Bnd_Box_HeaderFile
#include <Bnd_Box.hxx>
#endif
#ifndef _XIntTools_SurfaceRangeSampleMapHasher_HeaderFile
#include <XIntTools_SurfaceRangeSampleMapHasher.hxx>
#endif
#ifndef _XIntTools_DataMapOfSurfaceSampleBox_HeaderFile
#include <XIntTools_DataMapOfSurfaceSampleBox.hxx>
#endif
#ifndef _XIntTools_DataMapNodeOfDataMapOfSurfaceSampleBox_HeaderFile
#include <XIntTools_DataMapNodeOfDataMapOfSurfaceSampleBox.hxx>
#endif
 

#define TheKey XIntTools_SurfaceRangeSample
#define TheKey_hxx <XIntTools_SurfaceRangeSample.hxx>
#define TheItem Bnd_Box
#define TheItem_hxx <Bnd_Box.hxx>
#define Hasher XIntTools_SurfaceRangeSampleMapHasher
#define Hasher_hxx <XIntTools_SurfaceRangeSampleMapHasher.hxx>
#define TCollection_DataMapNode XIntTools_DataMapNodeOfDataMapOfSurfaceSampleBox
#define TCollection_DataMapNode_hxx <XIntTools_DataMapNodeOfDataMapOfSurfaceSampleBox.hxx>
#define TCollection_DataMapIterator XIntTools_DataMapIteratorOfDataMapOfSurfaceSampleBox
#define TCollection_DataMapIterator_hxx <XIntTools_DataMapIteratorOfDataMapOfSurfaceSampleBox.hxx>
#define Handle_TCollection_DataMapNode Handle_XIntTools_DataMapNodeOfDataMapOfSurfaceSampleBox
#define TCollection_DataMapNode_Type_() XIntTools_DataMapNodeOfDataMapOfSurfaceSampleBox_Type_()
#define TCollection_DataMap XIntTools_DataMapOfSurfaceSampleBox
#define TCollection_DataMap_hxx <XIntTools_DataMapOfSurfaceSampleBox.hxx>
#include <TCollection_DataMapIterator.gxx>

