// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_ListNodeOfListOfSurfaceRangeSample.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XIntTools_SurfaceRangeSample_HeaderFile
#include <XIntTools_SurfaceRangeSample.hxx>
#endif
#ifndef _XIntTools_ListOfSurfaceRangeSample_HeaderFile
#include <XIntTools_ListOfSurfaceRangeSample.hxx>
#endif
#ifndef _XIntTools_ListIteratorOfListOfSurfaceRangeSample_HeaderFile
#include <XIntTools_ListIteratorOfListOfSurfaceRangeSample.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XIntTools_ListNodeOfListOfSurfaceRangeSample)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XIntTools_ListNodeOfListOfSurfaceRangeSample)


IMPLEMENT_DOWNCAST(XIntTools_ListNodeOfListOfSurfaceRangeSample,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XIntTools_ListNodeOfListOfSurfaceRangeSample)


#define Item XIntTools_SurfaceRangeSample
#define Item_hxx <XIntTools_SurfaceRangeSample.hxx>
#define TCollection_ListNode XIntTools_ListNodeOfListOfSurfaceRangeSample
#define TCollection_ListNode_hxx <XIntTools_ListNodeOfListOfSurfaceRangeSample.hxx>
#define TCollection_ListIterator XIntTools_ListIteratorOfListOfSurfaceRangeSample
#define TCollection_ListIterator_hxx <XIntTools_ListIteratorOfListOfSurfaceRangeSample.hxx>
#define Handle_TCollection_ListNode Handle_XIntTools_ListNodeOfListOfSurfaceRangeSample
#define TCollection_ListNode_Type_() XIntTools_ListNodeOfListOfSurfaceRangeSample_Type_()
#define TCollection_List XIntTools_ListOfSurfaceRangeSample
#define TCollection_List_hxx <XIntTools_ListOfSurfaceRangeSample.hxx>
#include <TCollection_ListNode.gxx>

