// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_SequenceNodeOfSequenceOfCommonPrts.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XIntTools_CommonPrt_HeaderFile
#include <XIntTools_CommonPrt.hxx>
#endif
#ifndef _XIntTools_SequenceOfCommonPrts_HeaderFile
#include <XIntTools_SequenceOfCommonPrts.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XIntTools_SequenceNodeOfSequenceOfCommonPrts)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XIntTools_SequenceNodeOfSequenceOfCommonPrts)


IMPLEMENT_DOWNCAST(XIntTools_SequenceNodeOfSequenceOfCommonPrts,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XIntTools_SequenceNodeOfSequenceOfCommonPrts)


#define SeqItem XIntTools_CommonPrt
#define SeqItem_hxx <XIntTools_CommonPrt.hxx>
#define TCollection_SequenceNode XIntTools_SequenceNodeOfSequenceOfCommonPrts
#define TCollection_SequenceNode_hxx <XIntTools_SequenceNodeOfSequenceOfCommonPrts.hxx>
#define Handle_TCollection_SequenceNode Handle_XIntTools_SequenceNodeOfSequenceOfCommonPrts
#define TCollection_SequenceNode_Type_() XIntTools_SequenceNodeOfSequenceOfCommonPrts_Type_()
#define TCollection_Sequence XIntTools_SequenceOfCommonPrts
#define TCollection_Sequence_hxx <XIntTools_SequenceOfCommonPrts.hxx>
#include <TCollection_SequenceNode.gxx>

