// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_SequenceOfRanges.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _XIntTools_Range_HeaderFile
#include <XIntTools_Range.hxx>
#endif
#ifndef _XIntTools_SequenceNodeOfSequenceOfRanges_HeaderFile
#include <XIntTools_SequenceNodeOfSequenceOfRanges.hxx>
#endif
 

#define SeqItem XIntTools_Range
#define SeqItem_hxx <XIntTools_Range.hxx>
#define TCollection_SequenceNode XIntTools_SequenceNodeOfSequenceOfRanges
#define TCollection_SequenceNode_hxx <XIntTools_SequenceNodeOfSequenceOfRanges.hxx>
#define Handle_TCollection_SequenceNode Handle_XIntTools_SequenceNodeOfSequenceOfRanges
#define TCollection_SequenceNode_Type_() XIntTools_SequenceNodeOfSequenceOfRanges_Type_()
#define TCollection_Sequence XIntTools_SequenceOfRanges
#define TCollection_Sequence_hxx <XIntTools_SequenceOfRanges.hxx>
#include <TCollection_Sequence.gxx>

