// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_ListNodeOfListOfCurveRangeSample.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XIntTools_CurveRangeSample_HeaderFile
#include <XIntTools_CurveRangeSample.hxx>
#endif
#ifndef _XIntTools_ListOfCurveRangeSample_HeaderFile
#include <XIntTools_ListOfCurveRangeSample.hxx>
#endif
#ifndef _XIntTools_ListIteratorOfListOfCurveRangeSample_HeaderFile
#include <XIntTools_ListIteratorOfListOfCurveRangeSample.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XIntTools_ListNodeOfListOfCurveRangeSample)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XIntTools_ListNodeOfListOfCurveRangeSample)


IMPLEMENT_DOWNCAST(XIntTools_ListNodeOfListOfCurveRangeSample,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XIntTools_ListNodeOfListOfCurveRangeSample)


#define Item XIntTools_CurveRangeSample
#define Item_hxx <XIntTools_CurveRangeSample.hxx>
#define TCollection_ListNode XIntTools_ListNodeOfListOfCurveRangeSample
#define TCollection_ListNode_hxx <XIntTools_ListNodeOfListOfCurveRangeSample.hxx>
#define TCollection_ListIterator XIntTools_ListIteratorOfListOfCurveRangeSample
#define TCollection_ListIterator_hxx <XIntTools_ListIteratorOfListOfCurveRangeSample.hxx>
#define Handle_TCollection_ListNode Handle_XIntTools_ListNodeOfListOfCurveRangeSample
#define TCollection_ListNode_Type_() XIntTools_ListNodeOfListOfCurveRangeSample_Type_()
#define TCollection_List XIntTools_ListOfCurveRangeSample
#define TCollection_List_hxx <XIntTools_ListOfCurveRangeSample.hxx>
#include <TCollection_ListNode.gxx>

