// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_ListIteratorOfListOfBox.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XIntTools_ListOfBox_HeaderFile
#include <XIntTools_ListOfBox.hxx>
#endif
#ifndef _Bnd_Box_HeaderFile
#include <Bnd_Box.hxx>
#endif
#ifndef _XIntTools_ListNodeOfListOfBox_HeaderFile
#include <XIntTools_ListNodeOfListOfBox.hxx>
#endif
 

#define Item Bnd_Box
#define Item_hxx <Bnd_Box.hxx>
#define TCollection_ListNode XIntTools_ListNodeOfListOfBox
#define TCollection_ListNode_hxx <XIntTools_ListNodeOfListOfBox.hxx>
#define TCollection_ListIterator XIntTools_ListIteratorOfListOfBox
#define TCollection_ListIterator_hxx <XIntTools_ListIteratorOfListOfBox.hxx>
#define Handle_TCollection_ListNode Handle_XIntTools_ListNodeOfListOfBox
#define TCollection_ListNode_Type_() XIntTools_ListNodeOfListOfBox_Type_()
#define TCollection_List XIntTools_ListOfBox
#define TCollection_List_hxx <XIntTools_ListOfBox.hxx>
#include <TCollection_ListIterator.gxx>

