// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_SequenceOfCommonPrts.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _XIntTools_CommonPrt_HeaderFile
#include <XIntTools_CommonPrt.hxx>
#endif
#ifndef _XIntTools_SequenceNodeOfSequenceOfCommonPrts_HeaderFile
#include <XIntTools_SequenceNodeOfSequenceOfCommonPrts.hxx>
#endif
 

#define SeqItem XIntTools_CommonPrt
#define SeqItem_hxx <XIntTools_CommonPrt.hxx>
#define TCollection_SequenceNode XIntTools_SequenceNodeOfSequenceOfCommonPrts
#define TCollection_SequenceNode_hxx <XIntTools_SequenceNodeOfSequenceOfCommonPrts.hxx>
#define Handle_TCollection_SequenceNode Handle_XIntTools_SequenceNodeOfSequenceOfCommonPrts
#define TCollection_SequenceNode_Type_() XIntTools_SequenceNodeOfSequenceOfCommonPrts_Type_()
#define TCollection_Sequence XIntTools_SequenceOfCommonPrts
#define TCollection_Sequence_hxx <XIntTools_SequenceOfCommonPrts.hxx>
#include <TCollection_Sequence.gxx>

