// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_DataMapNodeOfDataMapOfCurveSampleBox.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XIntTools_CurveRangeSample_HeaderFile
#include <XIntTools_CurveRangeSample.hxx>
#endif
#ifndef _Bnd_Box_HeaderFile
#include <Bnd_Box.hxx>
#endif
#ifndef _XIntTools_CurveRangeSampleMapHasher_HeaderFile
#include <XIntTools_CurveRangeSampleMapHasher.hxx>
#endif
#ifndef _XIntTools_DataMapOfCurveSampleBox_HeaderFile
#include <XIntTools_DataMapOfCurveSampleBox.hxx>
#endif
#ifndef _XIntTools_DataMapIteratorOfDataMapOfCurveSampleBox_HeaderFile
#include <XIntTools_DataMapIteratorOfDataMapOfCurveSampleBox.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XIntTools_DataMapNodeOfDataMapOfCurveSampleBox)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XIntTools_DataMapNodeOfDataMapOfCurveSampleBox)


IMPLEMENT_DOWNCAST(XIntTools_DataMapNodeOfDataMapOfCurveSampleBox,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XIntTools_DataMapNodeOfDataMapOfCurveSampleBox)


#define TheKey XIntTools_CurveRangeSample
#define TheKey_hxx <XIntTools_CurveRangeSample.hxx>
#define TheItem Bnd_Box
#define TheItem_hxx <Bnd_Box.hxx>
#define Hasher XIntTools_CurveRangeSampleMapHasher
#define Hasher_hxx <XIntTools_CurveRangeSampleMapHasher.hxx>
#define TCollection_DataMapNode XIntTools_DataMapNodeOfDataMapOfCurveSampleBox
#define TCollection_DataMapNode_hxx <XIntTools_DataMapNodeOfDataMapOfCurveSampleBox.hxx>
#define TCollection_DataMapIterator XIntTools_DataMapIteratorOfDataMapOfCurveSampleBox
#define TCollection_DataMapIterator_hxx <XIntTools_DataMapIteratorOfDataMapOfCurveSampleBox.hxx>
#define Handle_TCollection_DataMapNode Handle_XIntTools_DataMapNodeOfDataMapOfCurveSampleBox
#define TCollection_DataMapNode_Type_() XIntTools_DataMapNodeOfDataMapOfCurveSampleBox_Type_()
#define TCollection_DataMap XIntTools_DataMapOfCurveSampleBox
#define TCollection_DataMap_hxx <XIntTools_DataMapOfCurveSampleBox.hxx>
#include <TCollection_DataMapNode.gxx>

