// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_ListOfCurveRangeSample.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XIntTools_ListIteratorOfListOfCurveRangeSample_HeaderFile
#include <XIntTools_ListIteratorOfListOfCurveRangeSample.hxx>
#endif
#ifndef _XIntTools_CurveRangeSample_HeaderFile
#include <XIntTools_CurveRangeSample.hxx>
#endif
#ifndef _XIntTools_ListNodeOfListOfCurveRangeSample_HeaderFile
#include <XIntTools_ListNodeOfListOfCurveRangeSample.hxx>
#endif
 

#define Item XIntTools_CurveRangeSample
#define Item_hxx <XIntTools_CurveRangeSample.hxx>
#define TCollection_ListNode XIntTools_ListNodeOfListOfCurveRangeSample
#define TCollection_ListNode_hxx <XIntTools_ListNodeOfListOfCurveRangeSample.hxx>
#define TCollection_ListIterator XIntTools_ListIteratorOfListOfCurveRangeSample
#define TCollection_ListIterator_hxx <XIntTools_ListIteratorOfListOfCurveRangeSample.hxx>
#define Handle_TCollection_ListNode Handle_XIntTools_ListNodeOfListOfCurveRangeSample
#define TCollection_ListNode_Type_() XIntTools_ListNodeOfListOfCurveRangeSample_Type_()
#define TCollection_List XIntTools_ListOfCurveRangeSample
#define TCollection_List_hxx <XIntTools_ListOfCurveRangeSample.hxx>
#include <TCollection_List.gxx>

