// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_ListOfSurfaceRangeSample.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XIntTools_ListIteratorOfListOfSurfaceRangeSample_HeaderFile
#include <XIntTools_ListIteratorOfListOfSurfaceRangeSample.hxx>
#endif
#ifndef _XIntTools_SurfaceRangeSample_HeaderFile
#include <XIntTools_SurfaceRangeSample.hxx>
#endif
#ifndef _XIntTools_ListNodeOfListOfSurfaceRangeSample_HeaderFile
#include <XIntTools_ListNodeOfListOfSurfaceRangeSample.hxx>
#endif
 

#define Item XIntTools_SurfaceRangeSample
#define Item_hxx <XIntTools_SurfaceRangeSample.hxx>
#define TCollection_ListNode XIntTools_ListNodeOfListOfSurfaceRangeSample
#define TCollection_ListNode_hxx <XIntTools_ListNodeOfListOfSurfaceRangeSample.hxx>
#define TCollection_ListIterator XIntTools_ListIteratorOfListOfSurfaceRangeSample
#define TCollection_ListIterator_hxx <XIntTools_ListIteratorOfListOfSurfaceRangeSample.hxx>
#define Handle_TCollection_ListNode Handle_XIntTools_ListNodeOfListOfSurfaceRangeSample
#define TCollection_ListNode_Type_() XIntTools_ListNodeOfListOfSurfaceRangeSample_Type_()
#define TCollection_List XIntTools_ListOfSurfaceRangeSample
#define TCollection_List_hxx <XIntTools_ListOfSurfaceRangeSample.hxx>
#include <TCollection_List.gxx>

