// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_MapIteratorOfMapOfCurveSample.hxx>

#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XIntTools_CurveRangeSample_HeaderFile
#include <XIntTools_CurveRangeSample.hxx>
#endif
#ifndef _XIntTools_CurveRangeSampleMapHasher_HeaderFile
#include <XIntTools_CurveRangeSampleMapHasher.hxx>
#endif
#ifndef _XIntTools_MapOfCurveSample_HeaderFile
#include <XIntTools_MapOfCurveSample.hxx>
#endif
#ifndef _XIntTools_StdMapNodeOfMapOfCurveSample_HeaderFile
#include <XIntTools_StdMapNodeOfMapOfCurveSample.hxx>
#endif
 

#define TheKey XIntTools_CurveRangeSample
#define TheKey_hxx <XIntTools_CurveRangeSample.hxx>
#define Hasher XIntTools_CurveRangeSampleMapHasher
#define Hasher_hxx <XIntTools_CurveRangeSampleMapHasher.hxx>
#define TCollection_StdMapNode XIntTools_StdMapNodeOfMapOfCurveSample
#define TCollection_StdMapNode_hxx <XIntTools_StdMapNodeOfMapOfCurveSample.hxx>
#define TCollection_MapIterator XIntTools_MapIteratorOfMapOfCurveSample
#define TCollection_MapIterator_hxx <XIntTools_MapIteratorOfMapOfCurveSample.hxx>
#define Handle_TCollection_StdMapNode Handle_XIntTools_StdMapNodeOfMapOfCurveSample
#define TCollection_StdMapNode_Type_() XIntTools_StdMapNodeOfMapOfCurveSample_Type_()
#define TCollection_Map XIntTools_MapOfCurveSample
#define TCollection_Map_hxx <XIntTools_MapOfCurveSample.hxx>
#include <TCollection_MapIterator.gxx>

