// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_QuickSortRange.hxx>

#ifndef _XIntTools_Range_HeaderFile
#include <XIntTools_Range.hxx>
#endif
#ifndef _XIntTools_Array1OfRange_HeaderFile
#include <XIntTools_Array1OfRange.hxx>
#endif
#ifndef _XIntTools_CompareRange_HeaderFile
#include <XIntTools_CompareRange.hxx>
#endif
 

#define Item XIntTools_Range
#define Item_hxx <XIntTools_Range.hxx>
#define Array XIntTools_Array1OfRange
#define Array_hxx <XIntTools_Array1OfRange.hxx>
#define Comparator XIntTools_CompareRange
#define Comparator_hxx <XIntTools_CompareRange.hxx>
#define SortTools_QuickSort XIntTools_QuickSortRange
#define SortTools_QuickSort_hxx <XIntTools_QuickSortRange.hxx>
#include <SortTools_QuickSort.gxx>

