// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_SequenceNodeOfSequenceOfRanges.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XIntTools_Range_HeaderFile
#include <XIntTools_Range.hxx>
#endif
#ifndef _XIntTools_SequenceOfRanges_HeaderFile
#include <XIntTools_SequenceOfRanges.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XIntTools_SequenceNodeOfSequenceOfRanges)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XIntTools_SequenceNodeOfSequenceOfRanges)


IMPLEMENT_DOWNCAST(XIntTools_SequenceNodeOfSequenceOfRanges,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XIntTools_SequenceNodeOfSequenceOfRanges)


#define SeqItem XIntTools_Range
#define SeqItem_hxx <XIntTools_Range.hxx>
#define TCollection_SequenceNode XIntTools_SequenceNodeOfSequenceOfRanges
#define TCollection_SequenceNode_hxx <XIntTools_SequenceNodeOfSequenceOfRanges.hxx>
#define Handle_TCollection_SequenceNode Handle_XIntTools_SequenceNodeOfSequenceOfRanges
#define TCollection_SequenceNode_Type_() XIntTools_SequenceNodeOfSequenceOfRanges_Type_()
#define TCollection_Sequence XIntTools_SequenceOfRanges
#define TCollection_Sequence_hxx <XIntTools_SequenceOfRanges.hxx>
#include <TCollection_SequenceNode.gxx>

