// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_IndexedDataMapNodeOfIndexedDataMapOfTransientAddress.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _Standard_Transient_HeaderFile
#include <Standard_Transient.hxx>
#endif
#ifndef _TColStd_MapTransientHasher_HeaderFile
#include <TColStd_MapTransientHasher.hxx>
#endif
#ifndef _XIntTools_IndexedDataMapOfTransientAddress_HeaderFile
#include <XIntTools_IndexedDataMapOfTransientAddress.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XIntTools_IndexedDataMapNodeOfIndexedDataMapOfTransientAddress)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XIntTools_IndexedDataMapNodeOfIndexedDataMapOfTransientAddress)


IMPLEMENT_DOWNCAST(XIntTools_IndexedDataMapNodeOfIndexedDataMapOfTransientAddress,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XIntTools_IndexedDataMapNodeOfIndexedDataMapOfTransientAddress)


#define TheKey Handle_Standard_Transient
#define TheKey_hxx <Standard_Transient.hxx>
#define TheItem Standard_Address
#define TheItem_hxx <Standard_Address.hxx>
#define Hasher TColStd_MapTransientHasher
#define Hasher_hxx <TColStd_MapTransientHasher.hxx>
#define TCollection_IndexedDataMapNode XIntTools_IndexedDataMapNodeOfIndexedDataMapOfTransientAddress
#define TCollection_IndexedDataMapNode_hxx <XIntTools_IndexedDataMapNodeOfIndexedDataMapOfTransientAddress.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XIntTools_IndexedDataMapNodeOfIndexedDataMapOfTransientAddress
#define TCollection_IndexedDataMapNode_Type_() XIntTools_IndexedDataMapNodeOfIndexedDataMapOfTransientAddress_Type_()
#define TCollection_IndexedDataMap XIntTools_IndexedDataMapOfTransientAddress
#define TCollection_IndexedDataMap_hxx <XIntTools_IndexedDataMapOfTransientAddress.hxx>
#include <TCollection_IndexedDataMapNode.gxx>

