// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XIntTools_SequenceNodeOfSequenceOfCurves.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XIntTools_Curve_HeaderFile
#include <XIntTools_Curve.hxx>
#endif
#ifndef _XIntTools_SequenceOfCurves_HeaderFile
#include <XIntTools_SequenceOfCurves.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XIntTools_SequenceNodeOfSequenceOfCurves)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XIntTools_SequenceNodeOfSequenceOfCurves)


IMPLEMENT_DOWNCAST(XIntTools_SequenceNodeOfSequenceOfCurves,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XIntTools_SequenceNodeOfSequenceOfCurves)


#define SeqItem XIntTools_Curve
#define SeqItem_hxx <XIntTools_Curve.hxx>
#define TCollection_SequenceNode XIntTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_hxx <XIntTools_SequenceNodeOfSequenceOfCurves.hxx>
#define Handle_TCollection_SequenceNode Handle_XIntTools_SequenceNodeOfSequenceOfCurves
#define TCollection_SequenceNode_Type_() XIntTools_SequenceNodeOfSequenceOfCurves_Type_()
#define TCollection_Sequence XIntTools_SequenceOfCurves
#define TCollection_Sequence_hxx <XIntTools_SequenceOfCurves.hxx>
#include <TCollection_SequenceNode.gxx>

