// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_IndexedDataMapOfVertexListEdgeInfo.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _XBOP_ListOfEdgeInfo_HeaderFile
#include <XBOP_ListOfEdgeInfo.hxx>
#endif
#ifndef _TopTools_ShapeMapHasher_HeaderFile
#include <TopTools_ShapeMapHasher.hxx>
#endif
#ifndef _XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo_HeaderFile
#include <XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo.hxx>
#endif
 

#define TheKey TopoDS_Shape
#define TheKey_hxx <TopoDS_Shape.hxx>
#define TheItem XBOP_ListOfEdgeInfo
#define TheItem_hxx <XBOP_ListOfEdgeInfo.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <TopTools_ShapeMapHasher.hxx>
#define TCollection_IndexedDataMapNode XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo
#define TCollection_IndexedDataMapNode_hxx <XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo
#define TCollection_IndexedDataMapNode_Type_() XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo_Type_()
#define TCollection_IndexedDataMap XBOP_IndexedDataMapOfVertexListEdgeInfo
#define TCollection_IndexedDataMap_hxx <XBOP_IndexedDataMapOfVertexListEdgeInfo.hxx>
#include <TCollection_IndexedDataMap.gxx>

