// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListNodeOfListOfConnexityBlock.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOP_ConnexityBlock_HeaderFile
#include <XBOP_ConnexityBlock.hxx>
#endif
#ifndef _XBOP_ListOfConnexityBlock_HeaderFile
#include <XBOP_ListOfConnexityBlock.hxx>
#endif
#ifndef _XBOP_ListIteratorOfListOfConnexityBlock_HeaderFile
#include <XBOP_ListIteratorOfListOfConnexityBlock.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOP_ListNodeOfListOfConnexityBlock)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOP_ListNodeOfListOfConnexityBlock)


IMPLEMENT_DOWNCAST(XBOP_ListNodeOfListOfConnexityBlock,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOP_ListNodeOfListOfConnexityBlock)


#define Item XBOP_ConnexityBlock
#define Item_hxx <XBOP_ConnexityBlock.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfConnexityBlock
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfConnexityBlock.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfConnexityBlock
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfConnexityBlock.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfConnexityBlock
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfConnexityBlock_Type_()
#define TCollection_List XBOP_ListOfConnexityBlock
#define TCollection_List_hxx <XBOP_ListOfConnexityBlock.hxx>
#include <TCollection_ListNode.gxx>

