// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListIteratorOfListOfConnexityBlock.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOP_ListOfConnexityBlock_HeaderFile
#include <XBOP_ListOfConnexityBlock.hxx>
#endif
#ifndef _XBOP_ConnexityBlock_HeaderFile
#include <XBOP_ConnexityBlock.hxx>
#endif
#ifndef _XBOP_ListNodeOfListOfConnexityBlock_HeaderFile
#include <XBOP_ListNodeOfListOfConnexityBlock.hxx>
#endif
 

#define Item XBOP_ConnexityBlock
#define Item_hxx <XBOP_ConnexityBlock.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfConnexityBlock
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfConnexityBlock.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfConnexityBlock
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfConnexityBlock.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfConnexityBlock
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfConnexityBlock_Type_()
#define TCollection_List XBOP_ListOfConnexityBlock
#define TCollection_List_hxx <XBOP_ListOfConnexityBlock.hxx>
#include <TCollection_ListIterator.gxx>

