// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListIteratorOfListOfCheckResult.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOP_ListOfCheckResult_HeaderFile
#include <XBOP_ListOfCheckResult.hxx>
#endif
#ifndef _XBOP_CheckResult_HeaderFile
#include <XBOP_CheckResult.hxx>
#endif
#ifndef _XBOP_ListNodeOfListOfCheckResult_HeaderFile
#include <XBOP_ListNodeOfListOfCheckResult.hxx>
#endif
 

#define Item XBOP_CheckResult
#define Item_hxx <XBOP_CheckResult.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfCheckResult
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfCheckResult.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfCheckResult
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfCheckResult.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfCheckResult
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfCheckResult_Type_()
#define TCollection_List XBOP_ListOfCheckResult
#define TCollection_List_hxx <XBOP_ListOfCheckResult.hxx>
#include <TCollection_ListIterator.gxx>

