// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _XBOP_ListOfEdgeInfo_HeaderFile
#include <XBOP_ListOfEdgeInfo.hxx>
#endif
#ifndef _TopTools_ShapeMapHasher_HeaderFile
#include <TopTools_ShapeMapHasher.hxx>
#endif
#ifndef _XBOP_IndexedDataMapOfVertexListEdgeInfo_HeaderFile
#include <XBOP_IndexedDataMapOfVertexListEdgeInfo.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo)


IMPLEMENT_DOWNCAST(XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo)


#define TheKey TopoDS_Shape
#define TheKey_hxx <TopoDS_Shape.hxx>
#define TheItem XBOP_ListOfEdgeInfo
#define TheItem_hxx <XBOP_ListOfEdgeInfo.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <TopTools_ShapeMapHasher.hxx>
#define TCollection_IndexedDataMapNode XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo
#define TCollection_IndexedDataMapNode_hxx <XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo
#define TCollection_IndexedDataMapNode_Type_() XBOP_IndexedDataMapNodeOfIndexedDataMapOfVertexListEdgeInfo_Type_()
#define TCollection_IndexedDataMap XBOP_IndexedDataMapOfVertexListEdgeInfo
#define TCollection_IndexedDataMap_hxx <XBOP_IndexedDataMapOfVertexListEdgeInfo.hxx>
#include <TCollection_IndexedDataMapNode.gxx>

