// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListNodeOfListOfEdgeInfo.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOP_EdgeInfo_HeaderFile
#include <XBOP_EdgeInfo.hxx>
#endif
#ifndef _XBOP_ListOfEdgeInfo_HeaderFile
#include <XBOP_ListOfEdgeInfo.hxx>
#endif
#ifndef _XBOP_ListIteratorOfListOfEdgeInfo_HeaderFile
#include <XBOP_ListIteratorOfListOfEdgeInfo.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOP_ListNodeOfListOfEdgeInfo)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOP_ListNodeOfListOfEdgeInfo)


IMPLEMENT_DOWNCAST(XBOP_ListNodeOfListOfEdgeInfo,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOP_ListNodeOfListOfEdgeInfo)


#define Item XBOP_EdgeInfo
#define Item_hxx <XBOP_EdgeInfo.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfEdgeInfo
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfEdgeInfo.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfEdgeInfo
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfEdgeInfo.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfEdgeInfo
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfEdgeInfo_Type_()
#define TCollection_List XBOP_ListOfEdgeInfo
#define TCollection_List_hxx <XBOP_ListOfEdgeInfo.hxx>
#include <TCollection_ListNode.gxx>

