// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListIteratorOfListOfListOfLoop.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOP_ListOfListOfLoop_HeaderFile
#include <XBOP_ListOfListOfLoop.hxx>
#endif
#ifndef _XBOP_ListOfLoop_HeaderFile
#include <XBOP_ListOfLoop.hxx>
#endif
#ifndef _XBOP_ListNodeOfListOfListOfLoop_HeaderFile
#include <XBOP_ListNodeOfListOfListOfLoop.hxx>
#endif
 

#define Item XBOP_ListOfLoop
#define Item_hxx <XBOP_ListOfLoop.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfListOfLoop
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfListOfLoop.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfListOfLoop
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfListOfLoop.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfListOfLoop
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfListOfLoop_Type_()
#define TCollection_List XBOP_ListOfListOfLoop
#define TCollection_List_hxx <XBOP_ListOfListOfLoop.hxx>
#include <TCollection_ListIterator.gxx>

