// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListNodeOfListOfListOfLoop.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOP_ListOfLoop_HeaderFile
#include <XBOP_ListOfLoop.hxx>
#endif
#ifndef _XBOP_ListOfListOfLoop_HeaderFile
#include <XBOP_ListOfListOfLoop.hxx>
#endif
#ifndef _XBOP_ListIteratorOfListOfListOfLoop_HeaderFile
#include <XBOP_ListIteratorOfListOfListOfLoop.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOP_ListNodeOfListOfListOfLoop)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOP_ListNodeOfListOfListOfLoop)


IMPLEMENT_DOWNCAST(XBOP_ListNodeOfListOfListOfLoop,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOP_ListNodeOfListOfListOfLoop)


#define Item XBOP_ListOfLoop
#define Item_hxx <XBOP_ListOfLoop.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfListOfLoop
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfListOfLoop.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfListOfLoop
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfListOfLoop.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfListOfLoop
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfListOfLoop_Type_()
#define TCollection_List XBOP_ListOfListOfLoop
#define TCollection_List_hxx <XBOP_ListOfListOfLoop.hxx>
#include <TCollection_ListNode.gxx>

