// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListNodeOfListOfFaceInfo.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOP_FaceInfo_HeaderFile
#include <XBOP_FaceInfo.hxx>
#endif
#ifndef _XBOP_ListOfFaceInfo_HeaderFile
#include <XBOP_ListOfFaceInfo.hxx>
#endif
#ifndef _XBOP_ListIteratorOfListOfFaceInfo_HeaderFile
#include <XBOP_ListIteratorOfListOfFaceInfo.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOP_ListNodeOfListOfFaceInfo)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOP_ListNodeOfListOfFaceInfo)


IMPLEMENT_DOWNCAST(XBOP_ListNodeOfListOfFaceInfo,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOP_ListNodeOfListOfFaceInfo)


#define Item XBOP_FaceInfo
#define Item_hxx <XBOP_FaceInfo.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfFaceInfo
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfFaceInfo.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfFaceInfo
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfFaceInfo.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfFaceInfo
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfFaceInfo_Type_()
#define TCollection_List XBOP_ListOfFaceInfo
#define TCollection_List_hxx <XBOP_ListOfFaceInfo.hxx>
#include <TCollection_ListNode.gxx>

