// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_SequenceNodeOfSeqOfSeqOfShape.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _TopTools_SequenceOfShape_HeaderFile
#include <TopTools_SequenceOfShape.hxx>
#endif
#ifndef _XBOP_SeqOfSeqOfShape_HeaderFile
#include <XBOP_SeqOfSeqOfShape.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOP_SequenceNodeOfSeqOfSeqOfShape)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_SeqNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOP_SequenceNodeOfSeqOfSeqOfShape)


IMPLEMENT_DOWNCAST(XBOP_SequenceNodeOfSeqOfSeqOfShape,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOP_SequenceNodeOfSeqOfSeqOfShape)


#define SeqItem TopTools_SequenceOfShape
#define SeqItem_hxx <TopTools_SequenceOfShape.hxx>
#define TCollection_SequenceNode XBOP_SequenceNodeOfSeqOfSeqOfShape
#define TCollection_SequenceNode_hxx <XBOP_SequenceNodeOfSeqOfSeqOfShape.hxx>
#define Handle_TCollection_SequenceNode Handle_XBOP_SequenceNodeOfSeqOfSeqOfShape
#define TCollection_SequenceNode_Type_() XBOP_SequenceNodeOfSeqOfSeqOfShape_Type_()
#define TCollection_Sequence XBOP_SeqOfSeqOfShape
#define TCollection_Sequence_hxx <XBOP_SeqOfSeqOfShape.hxx>
#include <TCollection_SequenceNode.gxx>

