// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListNodeOfListOfCheckResult.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOP_CheckResult_HeaderFile
#include <XBOP_CheckResult.hxx>
#endif
#ifndef _XBOP_ListOfCheckResult_HeaderFile
#include <XBOP_ListOfCheckResult.hxx>
#endif
#ifndef _XBOP_ListIteratorOfListOfCheckResult_HeaderFile
#include <XBOP_ListIteratorOfListOfCheckResult.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOP_ListNodeOfListOfCheckResult)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOP_ListNodeOfListOfCheckResult)


IMPLEMENT_DOWNCAST(XBOP_ListNodeOfListOfCheckResult,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOP_ListNodeOfListOfCheckResult)


#define Item XBOP_CheckResult
#define Item_hxx <XBOP_CheckResult.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfCheckResult
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfCheckResult.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfCheckResult
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfCheckResult.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfCheckResult
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfCheckResult_Type_()
#define TCollection_List XBOP_ListOfCheckResult
#define TCollection_List_hxx <XBOP_ListOfCheckResult.hxx>
#include <TCollection_ListNode.gxx>

