// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListNodeOfListOfLoop.hxx>

#ifndef _Standard_Type_HeaderFile
#include <Standard_Type.hxx>
#endif

#ifndef _XBOP_Loop_HeaderFile
#include <XBOP_Loop.hxx>
#endif
#ifndef _XBOP_ListOfLoop_HeaderFile
#include <XBOP_ListOfLoop.hxx>
#endif
#ifndef _XBOP_ListIteratorOfListOfLoop_HeaderFile
#include <XBOP_ListIteratorOfListOfLoop.hxx>
#endif

 


IMPLEMENT_STANDARD_TYPE(XBOP_ListNodeOfListOfLoop)
IMPLEMENT_STANDARD_SUPERTYPE_ARRAY()
  STANDARD_TYPE(TCollection_MapNode),
  STANDARD_TYPE(MMgt_TShared),
  STANDARD_TYPE(Standard_Transient),

IMPLEMENT_STANDARD_SUPERTYPE_ARRAY_END()
IMPLEMENT_STANDARD_TYPE_END(XBOP_ListNodeOfListOfLoop)


IMPLEMENT_DOWNCAST(XBOP_ListNodeOfListOfLoop,Standard_Transient)
IMPLEMENT_STANDARD_RTTI(XBOP_ListNodeOfListOfLoop)


#define Item Handle_XBOP_Loop
#define Item_hxx <XBOP_Loop.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfLoop
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfLoop.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfLoop
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfLoop.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfLoop
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfLoop_Type_()
#define TCollection_List XBOP_ListOfLoop
#define TCollection_List_hxx <XBOP_ListOfLoop.hxx>
#include <TCollection_ListNode.gxx>

