// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListIteratorOfListOfFaceInfo.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOP_ListOfFaceInfo_HeaderFile
#include <XBOP_ListOfFaceInfo.hxx>
#endif
#ifndef _XBOP_FaceInfo_HeaderFile
#include <XBOP_FaceInfo.hxx>
#endif
#ifndef _XBOP_ListNodeOfListOfFaceInfo_HeaderFile
#include <XBOP_ListNodeOfListOfFaceInfo.hxx>
#endif
 

#define Item XBOP_FaceInfo
#define Item_hxx <XBOP_FaceInfo.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfFaceInfo
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfFaceInfo.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfFaceInfo
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfFaceInfo.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfFaceInfo
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfFaceInfo_Type_()
#define TCollection_List XBOP_ListOfFaceInfo
#define TCollection_List_hxx <XBOP_ListOfFaceInfo.hxx>
#include <TCollection_ListIterator.gxx>

