// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListIteratorOfListOfLoop.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOP_ListOfLoop_HeaderFile
#include <XBOP_ListOfLoop.hxx>
#endif
#ifndef _XBOP_Loop_HeaderFile
#include <XBOP_Loop.hxx>
#endif
#ifndef _XBOP_ListNodeOfListOfLoop_HeaderFile
#include <XBOP_ListNodeOfListOfLoop.hxx>
#endif
 

#define Item Handle_XBOP_Loop
#define Item_hxx <XBOP_Loop.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfLoop
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfLoop.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfLoop
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfLoop.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfLoop
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfLoop_Type_()
#define TCollection_List XBOP_ListOfLoop
#define TCollection_List_hxx <XBOP_ListOfLoop.hxx>
#include <TCollection_ListIterator.gxx>

