// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_IndexedDataMapOfSolidClassifier.hxx>

#ifndef _Standard_DomainError_HeaderFile
#include <Standard_DomainError.hxx>
#endif
#ifndef _Standard_OutOfRange_HeaderFile
#include <Standard_OutOfRange.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _TopoDS_Shape_HeaderFile
#include <TopoDS_Shape.hxx>
#endif
#ifndef _TopTools_ShapeMapHasher_HeaderFile
#include <TopTools_ShapeMapHasher.hxx>
#endif
#ifndef _XBOP_IndexedDataMapNodeOfIndexedDataMapOfSolidClassifier_HeaderFile
#include <XBOP_IndexedDataMapNodeOfIndexedDataMapOfSolidClassifier.hxx>
#endif
 

#define TheKey TopoDS_Shape
#define TheKey_hxx <TopoDS_Shape.hxx>
#define TheItem XBOP_PSoClassif
#define TheItem_hxx <XBOP_PSoClassif.hxx>
#define Hasher TopTools_ShapeMapHasher
#define Hasher_hxx <TopTools_ShapeMapHasher.hxx>
#define TCollection_IndexedDataMapNode XBOP_IndexedDataMapNodeOfIndexedDataMapOfSolidClassifier
#define TCollection_IndexedDataMapNode_hxx <XBOP_IndexedDataMapNodeOfIndexedDataMapOfSolidClassifier.hxx>
#define Handle_TCollection_IndexedDataMapNode Handle_XBOP_IndexedDataMapNodeOfIndexedDataMapOfSolidClassifier
#define TCollection_IndexedDataMapNode_Type_() XBOP_IndexedDataMapNodeOfIndexedDataMapOfSolidClassifier_Type_()
#define TCollection_IndexedDataMap XBOP_IndexedDataMapOfSolidClassifier
#define TCollection_IndexedDataMap_hxx <XBOP_IndexedDataMapOfSolidClassifier.hxx>
#include <TCollection_IndexedDataMap.gxx>

