// This file is generated by WOK (CPPExt).
// Please do not edit this file; modify original file instead.
// The copyright and license terms as defined for the original file apply to 
// this header file considered to be the "object code" form of the original source.

#include <XBOP_ListIteratorOfListOfEdgeInfo.hxx>

#ifndef _Standard_NoMoreObject_HeaderFile
#include <Standard_NoMoreObject.hxx>
#endif
#ifndef _Standard_NoSuchObject_HeaderFile
#include <Standard_NoSuchObject.hxx>
#endif
#ifndef _XBOP_ListOfEdgeInfo_HeaderFile
#include <XBOP_ListOfEdgeInfo.hxx>
#endif
#ifndef _XBOP_EdgeInfo_HeaderFile
#include <XBOP_EdgeInfo.hxx>
#endif
#ifndef _XBOP_ListNodeOfListOfEdgeInfo_HeaderFile
#include <XBOP_ListNodeOfListOfEdgeInfo.hxx>
#endif
 

#define Item XBOP_EdgeInfo
#define Item_hxx <XBOP_EdgeInfo.hxx>
#define TCollection_ListNode XBOP_ListNodeOfListOfEdgeInfo
#define TCollection_ListNode_hxx <XBOP_ListNodeOfListOfEdgeInfo.hxx>
#define TCollection_ListIterator XBOP_ListIteratorOfListOfEdgeInfo
#define TCollection_ListIterator_hxx <XBOP_ListIteratorOfListOfEdgeInfo.hxx>
#define Handle_TCollection_ListNode Handle_XBOP_ListNodeOfListOfEdgeInfo
#define TCollection_ListNode_Type_() XBOP_ListNodeOfListOfEdgeInfo_Type_()
#define TCollection_List XBOP_ListOfEdgeInfo
#define TCollection_List_hxx <XBOP_ListOfEdgeInfo.hxx>
#include <TCollection_ListIterator.gxx>

